@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package teksturepako.saltwaterpatcher.mixins;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;