@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package teksturepako.saltwaterpatcher.mixins.late;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;