@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package teksturepako.saltwaterpatcher.mixins.early;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;